### ISSUE TITLE
Upgrade EQT to new 1.0.0 version

### ISSUE THREAD

**Issue by paskino** [TomographicImaging/CILViewer#378]
The version of EQT is pinned to 0.7.1

https://github.com/vais-ral/CILViewer/blob/c33ace9a01601a29c30dc7ec9c266ae5cc1e1b73/Wrappers/Python/conda-recipe/meta.yaml#L38

**Comment by DanicaSTFC** [comment]
We want to pin it to >= 0.7.1 after releasing eqt v1.0.0
