### ISSUE TITLE
xyz press should update the slice shown

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/CILViewer#396]
when the image is rotated by pressing x or y or z, the slice shown changes and it is fixed for either x or y or z. When the mouse wheel is used or the slider is moved, the x,y,z view should be updated too, independent of the previous view

**Comment by paskino** [comment]
What slice number should you select?

**Comment by DanicaSTFC** [comment]
This is probably related to the viewers "linker", which I did not know existed when I opened the issue. I now assigned the linker PR to close this issue
