### ISSUE TITLE
Slider should disappear when only 1 slice is visualised

### ISSUE THREAD

**Issue by DanicaSTFC** [TomographicImaging/CILViewer#421]
When only 1 slice is visualised, the slider shows values between -1 and 0. The slider should not appear and only one slice should be shown.

This is connected to #420

**Comment by paskino** [comment]
Maybe visibility can be disabled by calling `VisibilityOff`

https://vtk.org/doc/nightly/html/classvtkProp.html#a41c22a68b45cf9be5fb1bb1dbca41277

**Comment by DanicaSTFC** [comment]
It is         

`sw = vtk.vtkSliderWidget()`
`sw.SetEnabled(0)`
